### ISSUE TITLE
Allow init on Resource types

### ISSUE THREAD

**Issue by kirahsapong** [TBD54566975/tbdex-swift#67]
OrderStatus and Quote structs should not be initializable since a client will never initialize an OrderStatus or Quote. 

In addition, we should add additional tests accepting stringified JSON and prettified JSON from our http data responses for completeness.

**Comment by blackgirlbytes** [comment]
i like this "DevTools for creating Offerings, OrderStatuses, and Quotes."

**Comment by angiejones** [comment]
that would be amazing
